export const formTexts = {
  en: {
    formTitle: 'Telesales Application Form',
    formSubtitle: 'Hollywood Clinics - Join Our Sales Team',
    personalInfoTitle: 'Personal Information',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email Address',
    emailPlaceholder: 'Enter your email address',
    phone: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    city: 'Current City',
    cityPlaceholder: 'Enter your current city',
    country: 'Country',
    countryPlaceholder: 'Enter your country',
    
    workExperienceTitle: 'Work Experience',
    telesalesExperience: 'Do you have previous experience in telesales?',
    yearsOfExperience: 'Years of Experience',
    selectYears: 'Select years of experience',
    noExperience: 'No experience',
    lessThanOne: 'Less than 1 year',
    oneToThree: '1-3 years',
    threeToFive: '3-5 years',
    fiveOrMore: '5+ years',
    previousRoles: 'Brief Description of Past Roles',
    previousRolesPlaceholder: 'Describe your previous telesales or sales roles...',
    
    communicationTitle: 'Communication & Skills',
    languages: 'Languages Spoken',
    languageOptions: [
      { value: 'english', label: 'English' },
      { value: 'arabic', label: 'Arabic' },
      { value: 'french', label: 'French' },
      { value: 'spanish', label: 'Spanish' },
      { value: 'german', label: 'German' },
      { value: 'other', label: 'Other' },
    ],
    communicationSkills: 'Phone Communication Skills Rating',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    needsImprovement: 'Needs Improvement',
    importantSkills: 'Important Skills for Telesales Agents (Select All That Apply)',
    skillsOptions: [
      { value: 'active-listening', label: 'Active Listening' },
      { value: 'persuasion', label: 'Persuasion' },
      { value: 'time-management', label: 'Time Management' },
      { value: 'product-knowledge', label: 'Product Knowledge' },
      { value: 'customer-service', label: 'Customer Service' },
      { value: 'persistence', label: 'Persistence' },
      { value: 'confidence', label: 'Confidence' },
      { value: 'negotiation', label: 'Negotiation' },
    ],
    
    availabilityTitle: 'Availability & Work Conditions',
    fullTimeAvailability: 'Are you available for full-time work?',
    startDate: 'When can you start?',
    
    motivationTitle: 'Motivation',
    whyApply: 'Why are you applying for this position?',
    motivationPlaceholder: 'Tell us why you are interested in joining Hollywood Clinics...',
    salesMotivation: 'What motivates you in sales?',
    salesMotivationPlaceholder: 'Describe what drives you to succeed in sales...',
    
    attachmentsTitle: 'Attachments',
    uploadCV: 'Upload Your CV (PDF or DOCX)',
    additionalDocuments: 'Additional Documents (Optional)',
    
    confirmInfo: 'I confirm that the information provided in this form is accurate and complete.',
    yes: 'Yes',
    no: 'No',
    
    submitButton: 'Submit Application',
    submitting: 'Submitting...',
    confirmRequiredError: 'Please confirm that your information is accurate.',
    submitError: 'An error occurred while submitting your application. Please try again.',
    successMessage: 'Application Submitted Successfully!',
    successDescription: 'Thank you for applying to Hollywood Clinics. We will review your application and contact you soon.',
    submitAnotherApplication: 'Submit Another Application',
  },
  ar: {
    formTitle: 'نموذج تطبيق البيع عن بعد',
    formSubtitle: 'عيادات هوليوود - انضم إلى فريق المبيعات الخاص بنا',
    personalInfoTitle: 'المعلومات الشخصية',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل اسمك الكامل',
    email: 'عنوان البريد الإلكتروني',
    emailPlaceholder: 'أدخل عنوان بريدك الإلكتروني',
    phone: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم هاتفك',
    city: 'المدينة الحالية',
    cityPlaceholder: 'أدخل مدينتك الحالية',
    country: 'الدولة',
    countryPlaceholder: 'أدخل دولتك',
    
    workExperienceTitle: 'الخبرة الوظيفية',
    telesalesExperience: 'هل لديك خبرة سابقة في البيع عن بعد؟',
    yearsOfExperience: 'سنوات الخبرة',
    selectYears: 'اختر سنوات الخبرة',
    noExperience: 'لا توجد خبرة',
    lessThanOne: 'أقل من سنة واحدة',
    oneToThree: '1-3 سنوات',
    threeToFive: '3-5 سنوات',
    fiveOrMore: '5 سنوات فأكثر',
    previousRoles: 'وصف موجز للأدوار السابقة',
    previousRolesPlaceholder: 'اشرح أدوارك السابقة في البيع عن بعد أو المبيعات...',
    
    communicationTitle: 'الاتصالات والمهارات',
    languages: 'اللغات المتحدثة',
    languageOptions: [
      { value: 'english', label: 'الإنجليزية' },
      { value: 'arabic', label: 'العربية' },
      { value: 'french', label: 'الفرنسية' },
      { value: 'spanish', label: 'الإسبانية' },
      { value: 'german', label: 'الألمانية' },
      { value: 'other', label: 'أخرى' },
    ],
    communicationSkills: 'تقييم مهارات الاتصال الهاتفي',
    excellent: 'ممتاز',
    good: 'جيد',
    fair: 'مقبول',
    needsImprovement: 'يحتاج إلى تحسين',
    importantSkills: 'المهارات المهمة لوكلاء البيع عن بعد (اختر كل ما ينطبق)',
    skillsOptions: [
      { value: 'active-listening', label: 'الاستماع النشط' },
      { value: 'persuasion', label: 'الإقناع' },
      { value: 'time-management', label: 'إدارة الوقت' },
      { value: 'product-knowledge', label: 'معرفة المنتج' },
      { value: 'customer-service', label: 'خدمة العملاء' },
      { value: 'persistence', label: 'المثابرة' },
      { value: 'confidence', label: 'الثقة' },
      { value: 'negotiation', label: 'المفاوضات' },
    ],
    
    availabilityTitle: 'التوفر وشروط العمل',
    fullTimeAvailability: 'هل أنت متاح للعمل بدوام كامل؟',
    startDate: 'متى يمكنك البدء؟',
    
    motivationTitle: 'الدافع والحافز',
    whyApply: 'لماذا تتقدم لهذا المنصب؟',
    motivationPlaceholder: 'أخبرنا لماذا أنت مهتم بالانضمام إلى عيادات هوليوود...',
    salesMotivation: 'ما الذي يحفزك في المبيعات؟',
    salesMotivationPlaceholder: 'اشرح ما يدفعك للنجاح في المبيعات...',
    
    attachmentsTitle: 'المرفقات',
    uploadCV: 'تحميل السيرة الذاتية الخاصة بك (PDF أو DOCX)',
    additionalDocuments: 'مستندات إضافية (اختياري)',
    
    confirmInfo: 'أؤكد أن المعلومات المقدمة في هذا النموذج دقيقة وكاملة.',
    yes: 'نعم',
    no: 'لا',
    
    submitButton: 'إرسال الطلب',
    submitting: 'جاري الإرسال...',
    confirmRequiredError: 'يرجى تأكيد أن معلوماتك دقيقة.',
    submitError: 'حدث خطأ أثناء إرسال طلبك. يرجى المحاولة مرة أخرى.',
    successMessage: 'تم إرسال الطلب بنجاح!',
    successDescription: 'شكراً لتقديمك طلباً للانضمام إلى عيادات هوليوود. سنقوم بمراجعة طلبك والتواصل معك قريباً.',
    submitAnotherApplication: 'إرسال طلب آخر',
  },
};
