export const formTexts = {
  en: {
    formTitle: 'Application Form',
    formSubtitle: 'Join Our Team',
    
    // Section 1: Basic Questions (same for everyone)
    basicInfoTitle: 'Basic Information',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email Address',
    emailPlaceholder: 'Enter your email address',
    phone: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    city: 'Country / City',
    cityPlaceholder: 'Enter your country and city',
    currentlyEmployed: 'Are you currently employed?',
    currentlyEmployedOptions: [
      { value: 'yes-fulltime', label: 'Yes (full-time)' },
      { value: 'yes-parttime', label: 'Yes (part-time)' },
      { value: 'no', label: 'No' },
    ],
    
    // Section 2: Position Selection (single-select)
    positionSelectionTitle: 'Position Selection',
    positionSelection: 'Which position are you applying for?',
    positionOptions: [
      { value: 'marketing-content-creator', label: 'Marketing/Content Creator' },
      { value: 'human-resources', label: 'Human Resources (HR)' },
      { value: 'telesales', label: 'Telesales' },
      { value: 'doctor', label: 'Doctor' },
      { value: 'finance-accounting', label: 'Finance/Accounting' },
      { value: 'receptionist', label: 'Receptionist' },
      { value: 'telesales-operations', label: 'Telesales & Operations Role' },
      { value: 'operations-manager', label: 'Operations Manager' },
      { value: 'other', label: 'Other (please specify)' },
    ],
    otherPosition: 'Other Position',
    otherPositionPlaceholder: 'Please specify the position',
    
    // Receptionist Role
    receptionistTitle: 'Receptionist Role Questions',
    receptionistExperience: 'Do you have previous experience as a receptionist or front desk staff?',
    receptionistYears: 'How many years of experience do you have in customer service or front desk roles?',
    receptionistYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '2-5', label: '2–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    receptionistTasks: 'Which of the following tasks have you performed before?',
    receptionistTaskOptions: [
      { value: 'answering-calls', label: 'Answering phone calls and emails' },
      { value: 'scheduling', label: 'Scheduling appointments' },
      { value: 'payments', label: 'Handling payments and billing' },
      { value: 'records', label: 'Managing client records' },
      { value: 'greeting', label: 'Greeting and assisting clients' },
    ],
    bookingSystems: 'Which booking or clinic management systems have you used?',
    bookingSystemsPlaceholder: 'List the systems you have experience with',
    handleDifficultClient: 'How would you handle a difficult client or a complaint?',
    handleDifficultClientPlaceholder: 'Describe your approach...',
    receptionistMotivation: 'What motivates you to work as a receptionist in a beauty clinic?',
    receptionistMotivationPlaceholder: 'Tell us what drives you...',
    handleMultipleTasks: 'Are you comfortable handling multiple tasks at the same time?',
    
    // Content Creator Role
    contentCreatorTitle: 'Content Creator: Professional Background',
    contentCreatorExperience: 'What best describes your experience?',
    contentCreatorExperienceOptions: [
      { value: 'professional', label: 'Professional / Experienced' },
      { value: 'entry-level', label: 'Entry-level / Beginner' },
      { value: 'other', label: 'Other (please specify)' },
    ],
    contentCreatorOtherExperience: 'Other Experience',
    contentCreatorOtherExperiencePlaceholder: 'Please specify',
    contentCreatorYears: 'How many years of experience do you have in your field?',
    contentCreatorYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '3-5', label: '3–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    professionalExperience: 'Briefly describe your professional experience.',
    professionalExperiencePlaceholder: 'Include previous roles, companies, or relevant projects.',
    platformsTitle: 'Skills & Tools',
    activePlatforms: 'Which platforms do you actively create content for?',
    platformOptions: [
      { value: 'instagram', label: 'Instagram' },
      { value: 'tiktok', label: 'TikTok' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'other-platform', label: 'Other (please specify)' },
    ],
    otherPlatform: 'Other Platform',
    otherPlatformPlaceholder: 'Please specify',
    contentSpecialization: 'What type of content do you specialize in?',
    contentTypeOptions: [
      { value: 'short-form', label: 'Short-form videos (Reels, TikToks, Shorts)' },
      { value: 'long-form', label: 'Long-form videos' },
      { value: 'photography', label: 'Photography' },
      { value: 'editing', label: 'Editing' },
      { value: 'voice-over', label: 'Voice-over content' },
      { value: 'educational', label: 'Educational content' },
      { value: 'promotional', label: 'Promotional/ads content' },
      { value: 'storytelling', label: 'Storytelling content' },
    ],
    toolsSoftware: 'Which tools/software do you use?',
    toolsOptions: [
      { value: 'capcut', label: 'CapCut' },
      { value: 'premiere-pro', label: 'Adobe Premiere Pro' },
      { value: 'final-cut', label: 'Final Cut Pro' },
      { value: 'photoshop', label: 'Photoshop' },
      { value: 'lightroom', label: 'Lightroom' },
      { value: 'canva', label: 'Canva' },
      { value: 'mobile-apps', label: 'Mobile editing apps' },
      { value: 'other-tools', label: 'Other (please specify)' },
    ],
    otherTools: 'Other Tools',
    otherToolsPlaceholder: 'Please specify',
    portfolioTitle: 'Portfolio / Work Samples',
    portfolioLinks: 'Please share links or upload samples of your work.',
    portfolioPlaceholder: 'Portfolio, documents, videos, images, or relevant projects.',
    
    // Telesales Role
    telesalesTitle: 'Telesales: Work Experience',
    telesalesExperience: 'Do you have previous experience in Telesales, Call Center, or Sales?',
    telesalesYears: 'If yes, how many years of experience do you have?',
    telesalesYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '3-5', label: '3–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    telesalesExperienceDescription: 'Please briefly describe your previous telesales or customer service experience.',
    telesalesExperiencePlaceholder: 'Include company names, products or services sold, and main responsibilities.',
    communicationTitle: 'Communication & Skills',
    languages: 'Which languages do you speak fluently?',
    languageOptions: [
      { value: 'english', label: 'English' },
      { value: 'arabic', label: 'Arabic' },
      { value: 'other', label: 'Other (please specify)' },
    ],
    otherLanguage: 'Other Language',
    otherLanguagePlaceholder: 'Please specify',
    phoneCommunicationRating: 'How would you rate your communication skills over the phone?',
    phoneCommunicationScale: '1 = Basic | 5 = Excellent',
    phoneRatingOptions: [
      { value: '1', label: '1 - Basic' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5 - Excellent' },
    ],
    mostImportantSkill: 'In your opinion, what is the most important skill for a successful Telesales Agent?',
    mostImportantSkillPlaceholder: 'Describe the skill and why it\'s important...',
    
    // HR Role
    hrTitle: 'Human Resources (HR) Role',
    hrExperience: 'Do you have previous experience in HR or recruitment?',
    hrYears: 'How many years of HR-related experience do you have?',
    hrYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '2-5', label: '2–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    hrTasks: 'Which HR tasks have you handled before?',
    hrTaskOptions: [
      { value: 'recruitment', label: 'Recruitment & screening' },
      { value: 'interviews', label: 'Interviews' },
      { value: 'onboarding', label: 'Onboarding' },
      { value: 'employee-records', label: 'Employee records' },
      { value: 'hr-administration', label: 'HR administration' },
    ],
    handleConfidential: 'How do you handle confidential information?',
    handleConfidentialPlaceholder: 'Describe your approach to confidentiality...',
    
    // Finance/Accounting Role
    financeTitle: 'Finance / Accounting Role',
    financeExperience: 'Do you have previous experience in finance or accounting?',
    financeYears: 'How many years of finance or accounting experience do you have?',
    financeYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '2-5', label: '2–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    financeTasks: 'Which tasks have you handled before?',
    financeTaskOptions: [
      { value: 'bookkeeping', label: 'Bookkeeping' },
      { value: 'invoicing', label: 'Invoicing' },
      { value: 'payroll', label: 'Payroll' },
      { value: 'financial-reports', label: 'Financial reports' },
      { value: 'tax-tasks', label: 'Tax-related tasks' },
    ],
    
    // Doctor Role
    doctorTitle: 'Doctor Role Questions',
    licensedToPractice: 'Are you currently licensed to practice medicine in this country?',
    medicalSpecialty: 'What is your medical specialty?',
    medicalSpecialtyPlaceholder: 'e.g., Dermatology, Aesthetic Medicine, General Practice, etc.',
    clinicalExperience: 'How many years of clinical experience do you have after graduation?',
    clinicalExperienceOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-3', label: '1–3 years' },
      { value: '3-5', label: '3–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    workExperienceType: 'Do you have experience working in clinics, hospitals, or medical centers?',
    workExperienceTypeOptions: [
      { value: 'clinics', label: 'Clinics' },
      { value: 'hospitals', label: 'Hospitals' },
      { value: 'both', label: 'Both' },
      { value: 'no-experience', label: 'No previous experience' },
    ],
    proceduresPerformed: 'Which of the following procedures or services have you performed before?',
    procedureOptions: [
      { value: 'consultations', label: 'Patient consultations' },
      { value: 'examinations', label: 'Medical examinations' },
      { value: 'aesthetic', label: 'Aesthetic procedures (e.g., Botox, fillers)' },
      { value: 'laser', label: 'Laser or device-based treatments' },
      { value: 'follow-up', label: 'Post-treatment follow-up' },
    ],
    certifications: 'Are you certified or trained in any specialized medical or aesthetic procedures?',
    certificationsPlaceholder: 'List your certifications and training...',
    patientSafety: 'How do you ensure patient safety and professional ethics in your work?',
    patientSafetyPlaceholder: 'Describe your approach to patient safety and ethics...',
    
    // Telesales & Operations Role
    telesalesOpsTitle: 'Telesales & Operations Role',
    telesalesOpsExperience: 'Do you have previous experience in telesales, customer coordination, or order operations?',
    telesalesOpsYears: 'How many years of experience do you have in sales, operations, or order management?',
    telesalesOpsYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '2-5', label: '2–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    telesalesOpsTasks: 'Which of the following tasks have you performed before?',
    telesalesOpsTaskOptions: [
      { value: 'confirm-orders', label: 'Calling customers to confirm orders or appointments' },
      { value: 'follow-up', label: 'Following up with leads or existing customers' },
      { value: 'tracking', label: 'Tracking orders or service requests' },
      { value: 'coordinating', label: 'Coordinating with internal teams (warehouse, clinic, delivery)' },
      { value: 'updating-systems', label: 'Updating customer or order information in systems' },
    ],
    crmExperience: 'Have you worked with CRM, order management, or tracking systems before?',
    handleUnhappyCustomer: 'How do you handle a situation where a customer is unhappy with a delay or issue in their order/service?',
    handleUnhappyCustomerPlaceholder: 'Describe your approach...',
    comfortableSalesOps: 'Are you comfortable working with both sales targets and operational tasks at the same time?',
    
    // Operations Manager Role
    opsManagerTitle: 'Operations Manager Role',
    opsManagerExperience: 'Do you have previous experience in operations management or clinic/business operations?',
    opsManagerYears: 'How many years of experience do you have in operations or management?',
    opsManagerYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '3-5', label: '3–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    opsManagerTasks: 'Which of the following tasks have you performed before?',
    opsManagerTaskOptions: [
      { value: 'staff-schedules', label: 'Managing staff schedules and workflows' },
      { value: 'coordinating-depts', label: 'Coordinating between departments (sales, reception, medical staff)' },
      { value: 'kpis', label: 'Tracking KPIs and performance metrics' },
      { value: 'process-improvement', label: 'Process improvement and SOP creation' },
      { value: 'inventory', label: 'Inventory, procurement, or resource management' },
    ],
    operationsSystems: 'Which systems or tools have you used to manage operations?',
    operationsSystemsPlaceholder: 'List the systems or tools...',
    handleConflicts: 'How do you handle conflicts or challenges within teams?',
    handleConflictsPlaceholder: 'Describe your approach...',
    opsManagerMotivation: 'What motivates you to work as an operations manager in a clinic or service-based business?',
    opsManagerMotivationPlaceholder: 'Tell us what drives you...',
    comfortableDecisions: 'Are you comfortable making operational decisions that impact multiple departments?',
    
    // Other Role
    otherRoleTitle: 'Other Role / General Questions',
    otherPositionName: 'What position are you applying for?',
    otherPositionNamePlaceholder: 'Enter the position name',
    otherFieldExperience: 'Do you have previous experience in this field or a related field?',
    otherYears: 'How many years of experience do you have?',
    otherYearsOptions: [
      { value: 'less-than-1', label: 'Less than 1 year' },
      { value: '1-2', label: '1–2 years' },
      { value: '3-5', label: '3–5 years' },
      { value: 'more-than-5', label: 'More than 5 years' },
    ],
    otherExperienceDescription: 'Briefly describe your previous experience or skills relevant to this role.',
    otherExperienceDescriptionPlaceholder: 'Describe your experience and skills...',
    comfortableMultipleTasks: 'Are you comfortable handling multiple tasks or responsibilities?',
    
    // Common Availability & Attachments
    availabilityTitle: 'Availability & Work Conditions',
    whenCanStart: 'When can you start?',
    whenCanStartOptions: [
      { value: 'immediately', label: 'Immediately' },
      { value: '2-weeks', label: 'Within 2 weeks' },
      { value: '1-month', label: 'Within 1 month' },
    ],
    whenCanStartShort: 'When can you start? (Short answer)',
    whenCanStartPlaceholder: 'Enter your availability date',
    workAvailability: 'Are you available full-time, part-time, or flexible?',
    workAvailabilityOptions: [
      { value: 'full-time', label: 'Full-time' },
      { value: 'part-time', label: 'Part-time' },
      { value: 'flexible', label: 'Flexible' },
    ],
    attachmentsTitle: 'Attachments',
    uploadCV: 'Upload your CV / Resume',
    uploadCVNote: 'PDF only, required',
    uploadAdditional: 'Upload additional work samples',
    uploadAdditionalNote: 'PDF, JPG, PNG, MP4, MOV (optional but recommended)',
    linkedinPortfolio: 'LinkedIn profile or portfolio (optional)',
    linkedinPortfolioPlaceholder: 'Enter your LinkedIn URL or portfolio link',
    agreeToStore: 'Do you agree to us storing your information for recruitment purposes?',
    
    // Common
    yes: 'Yes',
    no: 'No',
    confirmInfo: 'I confirm that the information provided is accurate and complete.',
    submitButton: 'Submit Application',
    submitting: 'Submitting...',
    confirmRequiredError: 'Please confirm that your information is accurate.',
    submitError: 'An error occurred while submitting your application. Please try again.',
    successMessage: 'Application Submitted Successfully!',
    successDescription: 'Thank you for applying. We will review your application and contact you soon.',
    submitAnotherApplication: 'Submit Another Application',
  },
  ar: {
    formTitle: 'نموذج التقديم',
    formSubtitle: 'انضم إلى فريقنا',
    
    // Section 1: Basic Questions
    basicInfoTitle: 'المعلومات الأساسية',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل اسمك الكامل',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'أدخل عنوان بريدك الإلكتروني',
    phone: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم هاتفك',
    city: 'الدولة / المدينة',
    cityPlaceholder: 'أدخل دولتك ومدينتك',
    currentlyEmployed: 'هل أنت موظف حالياً؟',
    currentlyEmployedOptions: [
      { value: 'yes-fulltime', label: 'نعم (دوام كامل)' },
      { value: 'yes-parttime', label: 'نعم (دوام جزئي)' },
      { value: 'no', label: 'لا' },
    ],
    
    // Section 2: Position Selection
    positionSelectionTitle: 'اختيار المنصب',
    positionSelection: 'ما هو المنصب الذي تتقدم له؟',
    positionOptions: [
      { value: 'marketing-content-creator', label: 'التسويق/صانع محتوى' },
      { value: 'human-resources', label: 'الموارد البشرية' },
      { value: 'telesales', label: 'البيع عن بعد' },
      { value: 'doctor', label: 'طبيب' },
      { value: 'finance-accounting', label: 'المالية/المحاسبة' },
      { value: 'receptionist', label: 'موظف استقبال' },
      { value: 'telesales-operations', label: 'البيع عن بعد والعمليات' },
      { value: 'operations-manager', label: 'مدير العمليات' },
      { value: 'other', label: 'أخرى (يرجى التحديد)' },
    ],
    otherPosition: 'منصب آخر',
    otherPositionPlaceholder: 'يرجى تحديد المنصب',
    
    // Receptionist Role
    receptionistTitle: 'أسئلة دور موظف الاستقبال',
    receptionistExperience: 'هل لديك خبرة سابقة كموظف استقبال أو في استقبال العملاء؟',
    receptionistYears: 'كم عدد سنوات الخبرة لديك في خدمة العملاء أو وظائف الاستقبال؟',
    receptionistYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '2-5', label: 'سنوات 5–2' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    receptionistTasks: 'أي من المهام التالية قمت بها من قبل؟',
    receptionistTaskOptions: [
      { value: 'answering-calls', label: 'الرد على المكالمات الهاتفية والبريد الإلكتروني' },
      { value: 'scheduling', label: 'جدولة المواعيد' },
      { value: 'payments', label: 'التعامل مع المدفوعات والفواتير' },
      { value: 'records', label: 'إدارة سجلات العملاء' },
      { value: 'greeting', label: 'استقبال ومساعدة العملاء' },
    ],
    bookingSystems: 'ما أنظمة الحجز أو إدارة العيادة التي استخدمتها؟',
    bookingSystemsPlaceholder: 'اذكر الأنظمة التي لديك خبرة بها',
    handleDifficultClient: 'كيف ستتعامل مع عميل صعب أو شكوى؟',
    handleDifficultClientPlaceholder: 'اشرح نهجك...',
    receptionistMotivation: 'ما الذي يحفزك للعمل كموظف استقبال في عيادة تجميل؟',
    receptionistMotivationPlaceholder: 'أخبرنا ما يدفعك...',
    handleMultipleTasks: 'هل أنت مرتاح للتعامل مع مهام متعددة في نفس الوقت؟',
    
    // Content Creator Role
    contentCreatorTitle: 'منشئ محتوى – الخلفية المهنية',
    contentCreatorExperience: 'ما الذي يصف خبرتك بشكل أفضل؟',
    contentCreatorExperienceOptions: [
      { value: 'professional', label: 'محترف / ذو خبرة' },
      { value: 'entry-level', label: 'مبتدئ / مستوى ابتدائي' },
      { value: 'other', label: 'آخر (يرجى التحديد)' },
    ],
    contentCreatorOtherExperience: 'خبرة أخرى',
    contentCreatorOtherExperiencePlaceholder: 'يرجى التحديد',
    contentCreatorYears: 'كم عدد سنوات الخبرة لديك في مجالك؟',
    contentCreatorYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '3-5', label: 'سنوات 5–3' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    professionalExperience: 'وصف مختصر لخبرتك المهنية.',
    professionalExperiencePlaceholder: 'اذكر المناصب السابقة، الشركات، أو المشاريع ذات الصلة.',
    platformsTitle: 'المهارات والأدوات',
    activePlatforms: 'على أي المنصات تقوم بإنشاء المحتوى بشكل نشط؟',
    platformOptions: [
      { value: 'instagram', label: 'إنستغرام' },
      { value: 'tiktok', label: 'تيك توك' },
      { value: 'youtube', label: 'يوتيوب' },
      { value: 'facebook', label: 'فيسبوك' },
      { value: 'other-platform', label: 'أخرى (يرجى التحديد)' },
    ],
    otherPlatform: 'منصة أخرى',
    otherPlatformPlaceholder: 'يرجى التحديد',
    contentSpecialization: 'ما نوع المحتوى الذي تتخصص به؟',
    contentTypeOptions: [
      { value: 'short-form', label: 'مقاطع فيديو قصيرة (Reels / TikTok / Shorts)' },
      { value: 'long-form', label: 'مقاطع فيديو طويلة' },
      { value: 'photography', label: 'التصوير الفوتوغرافي' },
      { value: 'editing', label: 'التحرير / المونتاج' },
      { value: 'voice-over', label: 'محتوى صوتي / تعليق صوتي' },
      { value: 'educational', label: 'محتوى تعليمي' },
      { value: 'promotional', label: 'محتوى ترويجي / إعلانات' },
      { value: 'storytelling', label: 'محتوى قصصي' },
    ],
    toolsSoftware: 'ما الأدوات أو البرامج التي تستخدمها؟',
    toolsOptions: [
      { value: 'capcut', label: 'CapCut' },
      { value: 'premiere-pro', label: 'Adobe Premiere Pro' },
      { value: 'final-cut', label: 'Final Cut Pro' },
      { value: 'photoshop', label: 'Photoshop' },
      { value: 'lightroom', label: 'Lightroom' },
      { value: 'canva', label: 'Canva' },
      { value: 'mobile-apps', label: 'تطبيقات تحرير على الهاتف' },
      { value: 'other-tools', label: 'أخرى (يرجى التحديد)' },
    ],
    otherTools: 'أدوات أخرى',
    otherToolsPlaceholder: 'يرجى التحديد',
    portfolioTitle: 'المحفظة / عينات العمل',
    portfolioLinks: 'يرجى مشاركة الروابط أو رفع عينات من عملك.',
    portfolioPlaceholder: 'المحفظة، المستندات، الفيديوهات، الصور، أو المشاريع ذات الصلة.',
    
    // Telesales Role
    telesalesTitle: 'البيع عن بعد: الخبرة العملية',
    telesalesExperience: 'هل لديك خبرة سابقة في المبيعات الهاتفية أو مراكز الاتصال أو المبيعات بشكل عام؟',
    telesalesYears: 'في حال كانت الإجابة نعم، كم عدد سنوات الخبرة لديك؟',
    telesalesYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'من سنة إلى سنتين' },
      { value: '3-5', label: 'من 3 إلى 5 سنوات' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    telesalesExperienceDescription: 'يرجى وصف خبرتك السابقة في المبيعات الهاتفية أو خدمة العملاء بإيجاز.',
    telesalesExperiencePlaceholder: 'يرجى ذكر أسماء الشركات، نوع المنتجات أو الخدمات المباعة، وأهم المهام التي قمت بها',
    communicationTitle: 'مهارات التواصل',
    languages: 'ما هي اللغات التي تتحدثها بطلاقة؟',
    languageOptions: [
      { value: 'english', label: 'الإنجليزية' },
      { value: 'arabic', label: 'العربية' },
      { value: 'other', label: 'أخرى (يرجى التوضيح)' },
    ],
    otherLanguage: 'لغة أخرى',
    otherLanguagePlaceholder: 'يرجى التوضيح',
    phoneCommunicationRating: 'كيف تقيم مهاراتك في التواصل عبر الهاتف؟',
    phoneCommunicationScale: '1 = أساسية | 5 = ممتازة',
    phoneRatingOptions: [
      { value: '1', label: '1 - أساسية' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5 - ممتازة' },
    ],
    mostImportantSkill: 'برأيك، ما هي أهم مهارة يجب أن يتمتع بها موظف المبيعات الهاتفية الناجح؟',
    mostImportantSkillPlaceholder: 'اشرح المهارة ولماذا هي مهمة...',
    
    // HR Role
    hrTitle: 'دور الموارد البشرية',
    hrExperience: 'هل لديك خبرة سابقة في الموارد البشرية أو التوظيف؟',
    hrYears: 'كم عدد سنوات الخبرة لديك في مجال الموارد البشرية؟',
    hrYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '2-5', label: 'سنوات 5–2' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    hrTasks: 'أي من مهام الموارد البشرية قمت بها من قبل؟',
    hrTaskOptions: [
      { value: 'recruitment', label: 'التوظيف والفرز' },
      { value: 'interviews', label: 'المقابلات' },
      { value: 'onboarding', label: 'التعيين والتوجيه' },
      { value: 'employee-records', label: 'ملفات الموظفين' },
      { value: 'hr-administration', label: 'الأعمال الإدارية للموارد البشرية' },
    ],
    handleConfidential: 'كيف تتعامل مع المعلومات السرية؟',
    handleConfidentialPlaceholder: 'اشرح نهجك في التعامل مع السرية...',
    
    // Finance/Accounting Role
    financeTitle: 'دور المالية / المحاسبة',
    financeExperience: 'هل لديك خبرة سابقة في المحاسبة أو الشؤون المالية؟',
    financeYears: 'كم عدد سنوات الخبرة لديك في المحاسبة أو المالية؟',
    financeYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '2-5', label: 'سنوات 5–2' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    financeTasks: 'أي من المهام المالية قمت بها من قبل؟',
    financeTaskOptions: [
      { value: 'bookkeeping', label: 'مسك الدفاتر' },
      { value: 'invoicing', label: 'الفواتير' },
      { value: 'payroll', label: 'الرواتب' },
      { value: 'financial-reports', label: 'التقارير المالية' },
      { value: 'tax-tasks', label: 'المهام الضريبية' },
    ],
    
    // Doctor Role
    doctorTitle: 'أسئلة دور الطبيب',
    licensedToPractice: 'هل لديك ترخيص ساري المفعول لمزاولة مهنة الطب في هذا البلد؟',
    medicalSpecialty: 'ما تخصصك الطبي؟',
    medicalSpecialtyPlaceholder: 'مثل: طب الجلد، الطب التجميلي، الطب العام، إلخ',
    clinicalExperience: 'كم عدد سنوات الخبرة السريرية لديك بعد التخرج؟',
    clinicalExperienceOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-3', label: 'سنوات 3–1' },
      { value: '3-5', label: 'سنوات 5–3' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    workExperienceType: 'هل لديك خبرة سابقة في العمل في عيادات أو مستشفيات أو مراكز طبية؟',
    workExperienceTypeOptions: [
      { value: 'clinics', label: 'عيادات' },
      { value: 'hospitals', label: 'مستشفيات' },
      { value: 'both', label: 'كليهما' },
      { value: 'no-experience', label: 'لا توجد خبرة سابقة' },
    ],
    proceduresPerformed: 'أي من الإجراءات أو الخدمات التالية قمت بها من قبل؟',
    procedureOptions: [
      { value: 'consultations', label: 'استشارات المرضى' },
      { value: 'examinations', label: 'الفحوصات الطبية' },
      { value: 'aesthetic', label: 'الإجراءات التجميلية (مثل البوتوكس والفيلر)' },
      { value: 'laser', label: 'العلاجات بالليزر أو الأجهزة الطبية' },
      { value: 'follow-up', label: 'المتابعة بعد العلاج' },
    ],
    certifications: 'هل لديك شهادات أو تدريبات معتمدة في إجراءات طبية أو تجميلية متخصصة؟',
    certificationsPlaceholder: 'اذكر شهاداتك وتدريباتك...',
    patientSafety: 'كيف تضمن سلامة المرضى والالتزام بالأخلاقيات المهنية في عملك؟',
    patientSafetyPlaceholder: 'اشرح نهجك في سلامة المرضى والأخلاقيات...',
    
    // Telesales & Operations Role
    telesalesOpsTitle: 'دور البيع عن بعد والعمليات',
    telesalesOpsExperience: 'هل لديك خبرة سابقة في المبيعات الهاتفية أو تنسيق العملاء أو العمليات؟',
    telesalesOpsYears: 'كم عدد سنوات الخبرة لديك في المبيعات أو العمليات أو إدارة الطلبات؟',
    telesalesOpsYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '2-5', label: 'سنوات 5–2' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    telesalesOpsTasks: 'أي من المهام التالية قمت بها من قبل؟',
    telesalesOpsTaskOptions: [
      { value: 'confirm-orders', label: 'الاتصال بالعملاء لتأكيد الطلبات أو المواعيد' },
      { value: 'follow-up', label: 'متابعة العملاء المحتملين أو الحاليين' },
      { value: 'tracking', label: 'تتبع الطلبات أو طلبات الخدمة' },
      { value: 'coordinating', label: 'التنسيق مع الفرق الداخلية (المخزن، العيادة، التوصيل)' },
      { value: 'updating-systems', label: 'تحديث بيانات العملاء أو الطلبات على الأنظمة' },
    ],
    crmExperience: 'هل سبق لك العمل على أنظمة CRM أو إدارة الطلبات أو التتبع؟',
    handleUnhappyCustomer: 'كيف ستتعامل مع عميل غير راضٍ بسبب تأخير أو مشكلة في الطلب أو الخدمة؟',
    handleUnhappyCustomerPlaceholder: 'اشرح نهجك...',
    comfortableSalesOps: 'هل أنت مرتاح للعمل على مهام المبيعات والأعمال التشغيلية في نفس الوقت؟',
    
    // Operations Manager Role
    opsManagerTitle: 'دور مدير العمليات',
    opsManagerExperience: 'هل لديك خبرة سابقة في إدارة العمليات أو إدارة الأعمال/العيادات؟',
    opsManagerYears: 'كم عدد سنوات الخبرة لديك في العمليات أو الإدارة؟',
    opsManagerYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '3-5', label: 'سنوات 5–3' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    opsManagerTasks: 'أي من المهام التالية قمت بها من قبل؟',
    opsManagerTaskOptions: [
      { value: 'staff-schedules', label: 'إدارة جداول الموظفين وسير العمل' },
      { value: 'coordinating-depts', label: 'التنسيق بين الأقسام (المبيعات، الاستقبال، الطاقم الطبي)' },
      { value: 'kpis', label: 'متابعة مؤشرات الأداء (KPIs) وقياس الأداء' },
      { value: 'process-improvement', label: 'تحسين العمليات وإنشاء الإجراءات التشغيلية (SOPs)' },
      { value: 'inventory', label: 'إدارة المخزون والمشتريات أو الموارد' },
    ],
    operationsSystems: 'ما الأنظمة أو الأدوات التي استخدمتها لإدارة العمليات؟',
    operationsSystemsPlaceholder: 'اذكر الأنظمة أو الأدوات...',
    handleConflicts: 'كيف تتعامل مع النزاعات أو التحديات داخل الفرق؟',
    handleConflictsPlaceholder: 'اشرح نهجك...',
    opsManagerMotivation: 'ما الذي يحفزك للعمل كمدير عمليات في عيادة أو مؤسسة خدمات؟',
    opsManagerMotivationPlaceholder: 'أخبرنا ما يدفعك...',
    comfortableDecisions: 'هل أنت مرتاح لاتخاذ قرارات تشغيلية تؤثر على عدة أقسام؟',
    
    // Other Role
    otherRoleTitle: 'منصب آخر / أسئلة عامة',
    otherPositionName: 'ما هو المنصب الذي تتقدم له؟',
    otherPositionNamePlaceholder: 'أدخل اسم المنصب',
    otherFieldExperience: 'هل لديك خبرة سابقة في هذا المجال أو مجال مشابه؟',
    otherYears: 'كم عدد سنوات الخبرة لديك؟',
    otherYearsOptions: [
      { value: 'less-than-1', label: 'أقل من سنة' },
      { value: '1-2', label: 'سنة 2–1' },
      { value: '3-5', label: 'سنوات 5–3' },
      { value: 'more-than-5', label: 'أكثر من 5 سنوات' },
    ],
    otherExperienceDescription: 'وصف مختصر لخبرتك السابقة أو مهاراتك ذات الصلة بهذا المنصب.',
    otherExperienceDescriptionPlaceholder: 'اشرح خبرتك ومهاراتك...',
    comfortableMultipleTasks: 'هل أنت مرتاح للتعامل مع مهام متعددة أو مسؤوليات مختلفة؟',
    
    // Common Availability & Attachments
    availabilityTitle: 'التوفر وظروف العمل',
    whenCanStart: 'متى يمكنك البدء؟',
    whenCanStartOptions: [
      { value: 'immediately', label: 'فوراً' },
      { value: '2-weeks', label: 'خلال أسبوعين' },
      { value: '1-month', label: 'خلال شهر' },
    ],
    whenCanStartShort: 'متى يمكنك البدء؟ (إجابة قصيرة)',
    whenCanStartPlaceholder: 'أدخل تاريخ توفرك',
    workAvailability: 'هل أنت متاح بدوام كامل، جزئي، أم مرن؟',
    workAvailabilityOptions: [
      { value: 'full-time', label: 'دوام كامل' },
      { value: 'part-time', label: 'دوام جزئي' },
      { value: 'flexible', label: 'مرن' },
    ],
    attachmentsTitle: 'المرفقات',
    uploadCV: 'تحميل سيرتك الذاتية',
    uploadCVNote: 'PDF فقط، مطلوب',
    uploadAdditional: 'رفع عينات إضافية من العمل',
    uploadAdditionalNote: 'PDF، JPG، PNG، MP4، MOV (اختياري لكن يُنصح به)',
    linkedinPortfolio: 'رابط ملف LinkedIn أو محفظة أعمالك (اختياري)',
    linkedinPortfolioPlaceholder: 'أدخل رابط LinkedIn أو المحفظة',
    agreeToStore: 'هل توافق على تخزين معلوماتك لأغراض التوظيف؟',
    
    // Common
    yes: 'نعم',
    no: 'لا',
    confirmInfo: 'أقّر بأن جميع المعلومات المقدمة في هذا النموذج صحيحة وكاملة.',
    submitButton: 'إرسال الطلب',
    submitting: 'جاري الإرسال...',
    confirmRequiredError: 'يرجى تأكيد أن معلوماتك دقيقة.',
    submitError: 'حدث خطأ أثناء إرسال طلبك. يرجى المحاولة مرة أخرى.',
    successMessage: 'تم إرسال الطلب بنجاح!',
    successDescription: 'شكراً لتقديمك طلباً. سنقوم بمراجعة طلبك والتواصل معك قريباً.',
    submitAnotherApplication: 'إرسال طلب آخر',
  },
};
